### ISSUE TITLE
run demo.py failed

### ISSUE THREAD

**Issue by zdm110** [1900zyh/3D-Human-Body-Shape#12]
run on ubuntu16.04 with python3.5, and install requirements.txt
python demo.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    from maya_widget import *
  File "/home/julian/workd/git_baseline/3D-Human-Body-Shape/src/maya_widget.py", line 8, in <module>
    from PyQt4 import QtGui, QtCore
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by zdm110** [comment]
I use sudo python demo.py to run and with below error,
Using TensorFlow backend.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f0eb22ba410>, trait: activated, old value: <undefined>, new value: True
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/local/lib/python3.5/dist-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/home/julian/workd/git_baseline/3D-Human-Body-Shape/src/maya_widget.py", line 55, in update_plot
    mlab.triangular_mesh(v[:, 0], v[:, 1], v[:, 2], f)
TypeError: string indices must be integers
Traceback (most recent call last):
  File "demo.py", line 228, in <module>
    show_app()
  File "demo.py", line 222, in show_app
    win = HumanShapeAnalysisDemo()
  File "demo.py", line 23, in __init__
    self.viewer3D = MayaviQWidget(container)
  File "/home/julian/workd/git_baseline/3D-Human-Body-Shape/src/maya_widget.py", line 72, in __init__
    layout.addWidget(self.ui)
TypeError: addWidget(self, QWidget, stretch: int = 0, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = 0): argument 1 has unexpected type 'QWidget'

**Comment by 1900zyh** [comment]
Hi @zdm110 ,
sorry for the late response, I have tried it on ubuntu16.04/win10/osx, and they all worked well.
the packages you need to install are listed in requirements.txt

Thanks,
Yanhong.

**Comment by JeanPaul20** [comment]
Thank you Yanhong,
Going to try again.
Greetings Jean Paul

Op ma 11 feb. 2019 02:02 schreef zyh <notifications@github.com:

**Comment by zdm110** [comment]
@1900zyh @JeanPaul20 
Thanks, I use Anaconda to install all package and works fine.

**Comment by JeanPaul20** [comment]
How did you fixe the mlab.triable error?

mlab.triangular_mesh(v[:, 0], v[:, 1], v[:, 2], f)
TypeError: string indices must be integers

Thank you
Jean Paul

**Comment by zdm110** [comment]
Hi JeanPaul20,
actually I still have the error, but it could run.

**Comment by 1900zyh** [comment]
This problem only happened when the widget begins running, which will become normal when you further test the demo. I have fixed it.
